/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Monay Portfolio Service
 * Gateway service for portfolio data enriched with live market prices
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EnrichedPortfolio,
  GetEnrichedPortfolioApiV1PortfolioEnrichedGetParams,
  HTTPValidationError
} from '../portfolio.schemas';

import { customInstance } from '.././mutator';




/**
 * @summary Get Enriched Portfolio
 */
export type getEnrichedPortfolioApiV1PortfolioEnrichedGetResponse200 = {
  data: EnrichedPortfolio
  status: 200
}

export type getEnrichedPortfolioApiV1PortfolioEnrichedGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getEnrichedPortfolioApiV1PortfolioEnrichedGetResponseSuccess = (getEnrichedPortfolioApiV1PortfolioEnrichedGetResponse200) & {
  headers: Headers;
};
export type getEnrichedPortfolioApiV1PortfolioEnrichedGetResponseError = (getEnrichedPortfolioApiV1PortfolioEnrichedGetResponse422) & {
  headers: Headers;
};

export type getEnrichedPortfolioApiV1PortfolioEnrichedGetResponse = (getEnrichedPortfolioApiV1PortfolioEnrichedGetResponseSuccess | getEnrichedPortfolioApiV1PortfolioEnrichedGetResponseError)

export const getGetEnrichedPortfolioApiV1PortfolioEnrichedGetUrl = (params?: GetEnrichedPortfolioApiV1PortfolioEnrichedGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/portfolio/enriched?${stringifiedParams}` : `/api/v1/portfolio/enriched`
}

export const getEnrichedPortfolioApiV1PortfolioEnrichedGet = async (params?: GetEnrichedPortfolioApiV1PortfolioEnrichedGetParams, options?: RequestInit): Promise<getEnrichedPortfolioApiV1PortfolioEnrichedGetResponse> => {
  
  return customInstance<getEnrichedPortfolioApiV1PortfolioEnrichedGetResponse>(getGetEnrichedPortfolioApiV1PortfolioEnrichedGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetEnrichedPortfolioApiV1PortfolioEnrichedGetQueryKey = (params?: GetEnrichedPortfolioApiV1PortfolioEnrichedGetParams,) => {
    return [
    `/api/v1/portfolio/enriched`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetEnrichedPortfolioApiV1PortfolioEnrichedGetQueryOptions = <TData = Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>, TError = HTTPValidationError>(params?: GetEnrichedPortfolioApiV1PortfolioEnrichedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEnrichedPortfolioApiV1PortfolioEnrichedGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>> = ({ signal }) => getEnrichedPortfolioApiV1PortfolioEnrichedGet(params, { signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEnrichedPortfolioApiV1PortfolioEnrichedGetQueryResult = NonNullable<Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>>
export type GetEnrichedPortfolioApiV1PortfolioEnrichedGetQueryError = HTTPValidationError


export function useGetEnrichedPortfolioApiV1PortfolioEnrichedGet<TData = Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>, TError = HTTPValidationError>(
 params: undefined |  GetEnrichedPortfolioApiV1PortfolioEnrichedGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>,
          TError,
          Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEnrichedPortfolioApiV1PortfolioEnrichedGet<TData = Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>, TError = HTTPValidationError>(
 params?: GetEnrichedPortfolioApiV1PortfolioEnrichedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>,
          TError,
          Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEnrichedPortfolioApiV1PortfolioEnrichedGet<TData = Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>, TError = HTTPValidationError>(
 params?: GetEnrichedPortfolioApiV1PortfolioEnrichedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Enriched Portfolio
 */

export function useGetEnrichedPortfolioApiV1PortfolioEnrichedGet<TData = Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>, TError = HTTPValidationError>(
 params?: GetEnrichedPortfolioApiV1PortfolioEnrichedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnrichedPortfolioApiV1PortfolioEnrichedGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEnrichedPortfolioApiV1PortfolioEnrichedGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




