/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Monay Portfolio Service
 * Gateway service for portfolio data enriched with live market prices
 * OpenAPI spec version: 0.1.0
 */
export interface ChartPoint {
  timestamp: string;
  open: number | null;
  high: number | null;
  low: number | null;
  close: number | null;
  volume: number | null;
}

export interface ChartResponse {
  symbol: string;
  points: ChartPoint[];
}

export interface EnrichedHolding {
  account_id: string;
  account_name: string;
  symbol: string;
  name: string | null;
  quantity: number;
  cost_basis: number | null;
  current_price: number | null;
  market_value: number | null;
  unrealized_gain: number | null;
  unrealized_gain_percent: number | null;
  day_change: number | null;
  allocation_percent: number | null;
  asset_type: string | null;
}

export interface PortfolioSummary {
  total_value: number;
  total_cost_basis: number;
  total_unrealized_gain: number;
  day_change: number;
  day_change_percent: number;
  holding_count: number;
}

export interface EnrichedPortfolio {
  summary: PortfolioSummary;
  holdings: EnrichedHolding[];
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface Quote {
  symbol: string;
  name: string | null;
  price: number | null;
  change: number | null;
  change_percent: number | null;
  previous_close: number | null;
  volume: number | null;
  asset_type: string | null;
}

export interface QuotesResponse {
  quotes: Quote[];
}

export type GetQuotesApiV1QuotesGetParams = {
/**
 * Comma-separated symbols
 */
symbols: string;
};

export type GetChartApiV1ChartSymbolGetParams = {
/**
 * Time range: 1d, 5d, 1mo, 3mo, 6mo, 1y, 2y, 5y, max
 */
range?: string;
/**
 * Interval: 1d for daily (default), 5m for intraday
 */
interval?: string;
};

export type GetEnrichedPortfolioApiV1PortfolioEnrichedGetParams = {
/**
 * Filter by account ID
 */
account_id?: string | null;
};

