/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Monay Portfolio Service
 * Gateway service for portfolio data enriched with live market prices
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetQuotesApiV1QuotesGetParams,
  HTTPValidationError,
  QuotesResponse
} from '../portfolio.schemas';

import { customInstance } from '.././mutator';




/**
 * @summary Get Quotes
 */
export type getQuotesApiV1QuotesGetResponse200 = {
  data: QuotesResponse
  status: 200
}

export type getQuotesApiV1QuotesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getQuotesApiV1QuotesGetResponseSuccess = (getQuotesApiV1QuotesGetResponse200) & {
  headers: Headers;
};
export type getQuotesApiV1QuotesGetResponseError = (getQuotesApiV1QuotesGetResponse422) & {
  headers: Headers;
};

export type getQuotesApiV1QuotesGetResponse = (getQuotesApiV1QuotesGetResponseSuccess | getQuotesApiV1QuotesGetResponseError)

export const getGetQuotesApiV1QuotesGetUrl = (params: GetQuotesApiV1QuotesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/quotes?${stringifiedParams}` : `/api/v1/quotes`
}

export const getQuotesApiV1QuotesGet = async (params: GetQuotesApiV1QuotesGetParams, options?: RequestInit): Promise<getQuotesApiV1QuotesGetResponse> => {
  
  return customInstance<getQuotesApiV1QuotesGetResponse>(getGetQuotesApiV1QuotesGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetQuotesApiV1QuotesGetQueryKey = (params?: GetQuotesApiV1QuotesGetParams,) => {
    return [
    `/api/v1/quotes`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetQuotesApiV1QuotesGetQueryOptions = <TData = Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>, TError = HTTPValidationError>(params: GetQuotesApiV1QuotesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuotesApiV1QuotesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>> = ({ signal }) => getQuotesApiV1QuotesGet(params, { signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuotesApiV1QuotesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>>
export type GetQuotesApiV1QuotesGetQueryError = HTTPValidationError


export function useGetQuotesApiV1QuotesGet<TData = Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>, TError = HTTPValidationError>(
 params: GetQuotesApiV1QuotesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>,
          TError,
          Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuotesApiV1QuotesGet<TData = Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>, TError = HTTPValidationError>(
 params: GetQuotesApiV1QuotesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>,
          TError,
          Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuotesApiV1QuotesGet<TData = Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>, TError = HTTPValidationError>(
 params: GetQuotesApiV1QuotesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Quotes
 */

export function useGetQuotesApiV1QuotesGet<TData = Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>, TError = HTTPValidationError>(
 params: GetQuotesApiV1QuotesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuotesApiV1QuotesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuotesApiV1QuotesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




