/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Monay Portfolio Service
 * Gateway service for portfolio data enriched with live market prices
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChartResponse,
  GetChartApiV1ChartSymbolGetParams,
  HTTPValidationError
} from '../portfolio.schemas';

import { customInstance } from '.././mutator';




/**
 * @summary Get Chart
 */
export type getChartApiV1ChartSymbolGetResponse200 = {
  data: ChartResponse
  status: 200
}

export type getChartApiV1ChartSymbolGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getChartApiV1ChartSymbolGetResponseSuccess = (getChartApiV1ChartSymbolGetResponse200) & {
  headers: Headers;
};
export type getChartApiV1ChartSymbolGetResponseError = (getChartApiV1ChartSymbolGetResponse422) & {
  headers: Headers;
};

export type getChartApiV1ChartSymbolGetResponse = (getChartApiV1ChartSymbolGetResponseSuccess | getChartApiV1ChartSymbolGetResponseError)

export const getGetChartApiV1ChartSymbolGetUrl = (symbol: string,
    params?: GetChartApiV1ChartSymbolGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/chart/${symbol}?${stringifiedParams}` : `/api/v1/chart/${symbol}`
}

export const getChartApiV1ChartSymbolGet = async (symbol: string,
    params?: GetChartApiV1ChartSymbolGetParams, options?: RequestInit): Promise<getChartApiV1ChartSymbolGetResponse> => {
  
  return customInstance<getChartApiV1ChartSymbolGetResponse>(getGetChartApiV1ChartSymbolGetUrl(symbol,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetChartApiV1ChartSymbolGetQueryKey = (symbol?: string,
    params?: GetChartApiV1ChartSymbolGetParams,) => {
    return [
    `/api/v1/chart/${symbol}`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetChartApiV1ChartSymbolGetQueryOptions = <TData = Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>, TError = HTTPValidationError>(symbol: string,
    params?: GetChartApiV1ChartSymbolGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChartApiV1ChartSymbolGetQueryKey(symbol,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>> = ({ signal }) => getChartApiV1ChartSymbolGet(symbol,params, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(symbol), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChartApiV1ChartSymbolGetQueryResult = NonNullable<Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>>
export type GetChartApiV1ChartSymbolGetQueryError = HTTPValidationError


export function useGetChartApiV1ChartSymbolGet<TData = Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>, TError = HTTPValidationError>(
 symbol: string,
    params: undefined |  GetChartApiV1ChartSymbolGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>,
          TError,
          Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChartApiV1ChartSymbolGet<TData = Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>, TError = HTTPValidationError>(
 symbol: string,
    params?: GetChartApiV1ChartSymbolGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>,
          TError,
          Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChartApiV1ChartSymbolGet<TData = Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>, TError = HTTPValidationError>(
 symbol: string,
    params?: GetChartApiV1ChartSymbolGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Chart
 */

export function useGetChartApiV1ChartSymbolGet<TData = Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>, TError = HTTPValidationError>(
 symbol: string,
    params?: GetChartApiV1ChartSymbolGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChartApiV1ChartSymbolGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChartApiV1ChartSymbolGetQueryOptions(symbol,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




